name: Node.js CI

on:
  push:
    branches: [ "main" ]   # Runs on push to main
  pull_request:
    branches: [ "main" ]   # Runs on PR to main

jobs:
  build-and-test:
    runs-on: ubuntu-latest   # GitHub provides a VM automatically

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]   # Test on multiple Node versions

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Run linter (optional, if you use eslint)
        run: npm run lint

      - name: Build project (optional, if build step exists)
        run: npm run build
