 name: Node.js CI

on:
  push:
    branches: [ "main" ]   # Runs when code is pushed to main branch
  pull_request:
    branches: [ "main" ]   # Runs for PRs targeting main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]   # Test against multiple Node versions

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Lint code
      - name: Run ESLint
        run: npm run lint --if-present

      # Step 5: Run build (if available)
      - name: Build project
        run: npm run build --if-present

      # Step 6: Run tests
      - name: Run tests
        run: npm test
